name: Build & Deploy Marp slides

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Java for PlantUML
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Graphviz is required for many diagram types
      - name: Install Graphviz & PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz plantuml

      # Render all .puml → SVG (or PNG with -tpng)
      - name: Render PlantUML
        run: |
          mkdir -p diagrams
          plantuml -tsvg diagrams/*.puml

      # Build slides (HTML + PDF) via Marp
      - name: Use Marp CLI action to render
        uses: KoharaKazuya/marp-cli-action@v1
        with:
          input: slides.md
          allowLocalFiles: true
          html: true
          pdf: true
          output: dist/slides

      # Make index for Pages
      - name: Prepare site
        run: |
          mkdir -p dist
          # Ensure an index.html exists (point to slides.html)
          if [ ! -f dist/index.html ]; then
            echo '<meta http-equiv="refresh" content="0; url=slides.html">' > dist/index.html
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
