name: Build & Deploy Marp slides

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SLIDES_PATH: slides.md   # change if your deck isn't at repo root

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug: show files so we know SLIDES_PATH is right
      - run: |
          echo "Repo root:" && ls -la
          test -f "$SLIDES_PATH" || (echo "::error ::$SLIDES_PATH not found"; exit 1)

      # PlantUML (optional) + Graphviz
      - name: Install Graphviz & PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz plantuml
          mkdir -p diagrams
          plantuml -tsvg diagrams/*.puml || true

      # Marp CLI via Node (runs as current user; no perms issues)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Marp CLI
        run: npm i -g @marp-team/marp-cli

      - name: Build slides (HTML)
        run: |
          mkdir -p build
          marp "$SLIDES_PATH" --allow-local-files --html -o build/slides.html

      - name: Build slides (PDF)
        run: |
          # marp installs Chromium via Puppeteer; PDF needs it
          marp "$SLIDES_PATH" --allow-local-files --pdf -o build/slides.pdf

      - name: Assemble site
        run: |
          rm -rf site
          mkdir -p site/diagrams
          cp -r build/. site/
          if ls diagrams/*.svg >/dev/null 2>&1; then cp diagrams/*.svg site/diagrams/; fi
          cp site/slides.html site/index.html
          echo "site/ contents:" && ls -la site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
